# Generated by Django 3.1.12 on 2021-11-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20211120_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
