# Generated by Django 3.1.12 on 2021-10-26 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=12, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnpj', models.CharField(max_length=15, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSaida',
            fields=[
                ('registro', models.AutoField(primary_key=True, serialize=False)),
                ('diahora', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(default='exemplo', max_length=150)),
                ('telefone', models.CharField(default=1234567899, max_length=12)),
                ('endereco', models.CharField(default='teste', max_length=200)),
                ('email', models.EmailField(default='email@email.com', max_length=254)),
                ('cnpj', models.CharField(default=123456789123456, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('registro', models.AutoField(primary_key=True, serialize=False)),
                ('diahora', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasesupplier', to='operacoes.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('precounitario', models.IntegerField(default=1)),
                ('precototal', models.IntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleitem', to='estoque.produto')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salebillno', to='operacoes.registrosaida')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('precounitario', models.IntegerField(default=1)),
                ('precototal', models.IntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitem', to='estoque.produto')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasebillno', to='operacoes.registroentrada')),
            ],
        ),
    ]
