# Generated by Django 3.1.12 on 2021-11-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoentrada',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='produtosaida',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
