# Generated by Django 3.1.12 on 2021-11-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20211120_1515'),
        ('operacoes', '0002_auto_20211120_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosaida',
            name='quantidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
    ]
