# Generated by Django 3.1.12 on 2021-11-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0003_auto_20211120_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoentrada',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produtosaida',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
