# Generated by Django 3.1.12 on 2021-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0004_auto_20211123_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosaida',
            name='cnpj',
            field=models.CharField(default=12345678912345, max_length=15),
        ),
    ]
